-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgsvO0ofbVVVqjYYTN
m+4refNMAjQ1Css5cxkJorg+gNCgCgYIKoZIzj0DAQehRANCAASt9fRZn+NJ6n9P
O1aON+EoCkeL3RJfcOXk67Rug72jQIUbwRPp0DeCKxu0KnVUafK1urs/HNYcYKpi
kWVHMqi/
-----END PRIVATE KEY-----