// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_API_KEY_WEB'),
    appId: '1:76342007759:web:ec5cd1f83580a0fb3164ba',
    messagingSenderId: '76342007759',
    projectId: 'flutter-reagent-test',
    authDomain: 'flutter-reagent-test.firebaseapp.com',
    storageBucket: 'flutter-reagent-test.firebasestorage.app',
    measurementId: 'G-8CPPS6G70D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_API_KEY_ANDROID'),
    appId: '1:76342007759:android:1d8bec4e1e5955d43164ba',
    messagingSenderId: '76342007759',
    projectId: 'flutter-reagent-test',
    storageBucket: 'flutter-reagent-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_API_KEY_IOS'),
    appId: '1:76342007759:ios:2842920a81dc24613164ba',
    messagingSenderId: '76342007759',
    projectId: 'flutter-reagent-test',
    storageBucket: 'flutter-reagent-test.firebasestorage.app',
    iosClientId: '76342007759-mon4usabeh4a93i12i48eq6maj5qcdm5.apps.googleusercontent.com',
    iosBundleId: 'com.yousef.ctds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_API_KEY_MACOS'),
    appId: '1:76342007759:ios:2842920a81dc24613164ba',
    messagingSenderId: '76342007759',
    projectId: 'flutter-reagent-test',
    storageBucket: 'flutter-reagent-test.firebasestorage.app',
    iosClientId: '76342007759-mon4usabeh4a93i12i48eq6maj5qcdm5.apps.googleusercontent.com',
    iosBundleId: 'com.yousef.ctds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_API_KEY_WINDOWS'),
    appId: '1:76342007759:web:0318c3f7a6adef6e3164ba',
    messagingSenderId: '76342007759',
    projectId: 'flutter-reagent-test',
    authDomain: 'flutter-reagent-test.firebaseapp.com',
    storageBucket: 'flutter-reagent-test.firebasestorage.app',
    measurementId: 'G-VHXK936Q4Z',
  );

}